export const ActionTypes = {
    FETCH_USER_AGENT_DATA : "FETCH_USER_AGENT",
    ERROR_FETCH_USER_AGENT_DATA : "ERROR_FETCH_USER_AGENT",
    LOGIN_STATUS : 'LOGIN_STATUS',
    AGENT_STATUS : 'AGENT_STATUS',
    SINGLE_USER_DATA : 'SINGLE_USER_DATA'
};